name: Workflow01

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello, Amol Anerao
        run: echo "Hello, Amol Anerao"

      - name: Copy Repo
        uses: actions/checkout@v6

      - name: List Files
        run: ls -la 

      - name: Generate ASCII
        run: |
          sudo apt-get install -y figlet
          figlet "GH-200 Cohack"
          echo "------------------------------"
          figlet -f digital "GitHub Actions"
  
